const gamesData = [
    { name: "007 - From Russia with Love", size: "539.48 MB", link: "https://seulink.net/BZXkMH", category: "🗡️ Ação / Aventura" },
    { name: "101-in-1 Megamix", size: "498.26 MB", link: "https://seulink.net/PLcb0", category: "🎮 Plataforma / Puzzle / Família" },
    { name: "Aliens vs. Predator - Requiem", size: "279.62 MB", link: "https://seulink.net/T3Gl5v08l", category: "🔫 Tiro (TPS/FPS)" },
    { name: "Ape Escape Academy", size: "158.41 MB", link: "https://seulink.net/jyf6ORhh5", category: "🎮 Plataforma / Puzzle / Família" },
    { name: "Armored Core 3 Portable", size: "299.72 MB", link: "https://seulink.net/HXvamWKXgn", category: "🗡️ Ação / Aventura" },
    { name: "Assassin's Creed - Bloodlines", size: "541.49 MB", link: "https://seulink.net/yhSBc47zt", category: "🗡️ Ação / Aventura" },
    { name: "Avatar - The Last Airbender", size: "126.70 MB", link: "https://4br.me/E9sms", category: "🗡️ Ação / Aventura" },
    { name: "Battlezone", size: "165.88 MB", link: "https://seulink.net/hdvzq1hi04qzuri", category: "🔫 Tiro (TPS/FPS)" },
    { name: "Ben 10 - Protector of Earth", size: "593.00 MB", link: "https://seulink.net/v33WNDu", category: "🗡️ Ação / Aventura" },
    { name: "Bomberman", size: "55.83 MB", link: "https://seulink.net/OAEY", category: "🎮 Plataforma / Puzzle / Família" },
    { name: "Brave Story - New Traveler", size: "132.06 MB", link: "https://seulink.net/hiImDh", category: "🧙‍♂️ RPG / Ação" },
    { name: "Burnout Dominator", size: "408.65 MB", link: "https://seulink.net/w4UL", category: "🏎️ Corrida" },
    { name: "Burnout Legends", size: "203.82 MB", link: "https://seulink.net/iA0ZvF", category: "🏎️ Corrida" },
    { name: "Cabela's African Safari", size: "432.61 MB", link: "https://seulink.net/3c3FWz", category: "🔫 Tiro (TPS/FPS)" },
    { name: "Cabela's Legendary Adventures", size: "374.58 MB", link: "https://seulink.net/T4OlYDAKss", category: "🔫 Tiro (TPS/FPS)" },
    { name: "Cabela's North American Adventures", size: "266.79 MB", link: "https://4br.me/YCE8E5krGR", category: "🔫 Tiro (TPS/FPS)" },
    { name: "Call of Duty - Roads to Victory", size: "478.74 MB", link: "https://seulink.net/YZdJ6pz3", category: "🔫 Tiro (TPS/FPS)" },
    { name: "Chili Con Carnage", size: "595.11 MB", link: "https://4br.me/FoEe5V", category: "🔫 Tiro (TPS/FPS)" },
    { name: "Coded Arms", size: "93.98 MB", link: "https://seulink.net/ou65nhYp", category: "🔫 Tiro (TPS/FPS)" },
    { name: "Crash of the Titans", size: "585.42 MB", link: "https://seulink.net/2k07ve", category: "🎮 Plataforma / Puzzle / Família" },
    { name: "Dead or Alive Paradise", size: "568.48 MB", link: "https://seulink.net/ZHFsHfK", category: "🌾 Simulação / Vida" },
    { name: "Dead to Rights - Reckoning", size: "104.21 MB", link: "https://seulink.net/r6pj", category: "🔫 Tiro (TPS/FPS)" },
    { name: "Death Jr.", size: "244.01 MB", link: "https://4br.me/oKFK1CDO", category: "🗡️ Ação / Aventura" },
    { name: "Def Jam - Fight for NY - The Takeover", size: "389.05 MB", link: "https://seulink.net/YDXkzjxOm", category: "🥊 Luta" },
    { name: "Dragon Ball Z - Shin Budokai", size: "208.91 MB", link: "https://4br.me/wMAn33C", category: "🥊 Luta" },
    { name: "Dragon Ball Z - Shin Budokai - Another Road", size: "335.92 MB", link: "https://seulink.digital/CqKWufVz", category: "🥊 Luta" },
    { name: "Dragoneer's Aria", size: "245.05 MB", link: "https://4br.me/Xe3KByaiT", category: "🧙‍♂️ RPG / Ação" },
    { name: "DreamWorks Shrek Smash N' Crash Racing", size: "241.12 MB", link: "https://seulink.net/IJe51", category: "🏎️ Corrida" },
    { name: "DreamWorks Shrek the Third", size: "364.54 MB", link: "https://seulink.net/UnTE", category: "🗡️ Ação / Aventura" },
    { name: "Dynasty Warriors", size: "115.77 MB", link: "https://seulink.net/4M1D5fRUr", category: "🗡️ Ação / Aventura" },
    { name: "Eragon", size: "162.61 MB", link: "https://seulink.net/qt9mko8", category: "🗡️ Ação / Aventura" },
    { name: "Exit", size: "63.96 MB", link: "https://seulink.net/IPMB", category: "🎮 Plataforma / Puzzle / Família" },
    { name: "FIFA Street 2", size: "219.07 MB", link: "https://seulink.net/elku", category: "🏆 Esportes" },
    { name: "FlatOut - Head On", size: "365.48 MB", link: "https://seulink.net/RPvFfwfM", category: "🏎️ Corrida" },
    { name: "Ford Racing Off Road", size: "334.98 MB", link: "https://seulink.net/7apu3c1Gu", category: "🏎️ Corrida" },
    { name: "Gladiator Begins", size: "341.59 MB", link: "https://seulink.net/ix851vM1zT", category: "🥊 Luta" },
    { name: "God of War - Ghost of Sparta", size: "1014.25 MB", link: "https://seulink.net/jftTXc", category: "🗡️ Ação / Aventura" },
    { name: "Grand Theft Auto - Chinatown Wars", size: "554.66 MB", link: "https://seulink.net/STT5PJn", category: "🌍 Mundo Aberto / Sandbox" },
    { name: "Grand Theft Auto - Liberty City Stories", size: "316.23 MB", link: "https://seulink.net/6cXbgzBds7", category: "🌍 Mundo Aberto / Sandbox" },
    { name: "Grand Theft Auto - Vice City Stories", size: "517.71 MB", link: "https://seulink.net/zPSs9EjZ", category: "🌍 Mundo Aberto / Sandbox" },
    { name: "Gripshift", size: "67.13 MB", link: "https://4br.me/3eMlQSh", category: "🎮 Plataforma / Puzzle / Família" },
    { name: "GUN Showdown", size: "601.54 MB", link: "https://seulink.net/s1Ezi", category: "🌍 Mundo Aberto / Sandbox" },
    { name: "Half-Minute Hero", size: "95.48 MB", link: "https://seulink.net/duZd88WM", category: "🧙‍♂️ RPG / Ação" },
    { name: "Hammerin' Hero", size: "99.11 MB", link: "https://4br.me/D8JEt9veM", category: "🎮 Plataforma / Puzzle / Família" },
    { name: "Hannspree Ten Kate Honda SBK Superbike World Championship", size: "150.60 MB", link: "https://seulink.net/uBiz5yOHW", category: "🏎️ Corrida" },
    { name: "Harvest Moon - Boy & Girl", size: "136.86 MB", link: "https://seulink.net/uUoNJ1teI", category: "🌾 Simulação / Vida" },
    { name: "Harvest Moon - Hero of Leaf Valley", size: "137.21 MB", link: "https://seulink.net/h1DMKzv", category: "🌾 Simulação / Vida" },
    { name: "Hot Wheels Ultimate Racing", size: "105.95 MB", link: "https://seulink.net/clOTbT", category: "🏎️ Corrida" },
    { name: "Infected", size: "529.81 MB", link: "https://seulink.net/djKokt7", category: "🔫 Tiro (TPS/FPS)" },
    { name: "Kao Challengers", size: "389.89 MB", link: "https://seulink.net/PYJBsT7", category: "🗡️ Ação / Aventura" },
    { name: "Kenka Bancho - Badass Rumble", size: "376.69 MB", link: "https://seulink.net/uQ0jBlTWT", category: "🥊 Luta" },
    { name: "Killzone - Liberation", size: "477.13 MB", link: "https://seulink.net/CVQf", category: "🔫 Tiro (TPS/FPS)" },
    { name: "LEGO Batman - The Videogame", size: "394.33 MB", link: "https://seulink.net/ydS8eLSb", category: "🗡️ Ação / Aventura" },
    { name: "LEGO Indiana Jones - The Original Adventures", size: "479.49 MB", link: "https://seulink.net/zzn1zTwlXD", category: "🗡️ Ação / Aventura" },
    { name: "Marvel Nemesis - Rise of the Imperfects", size: "121.66 MB", link: "https://4br.me/s4q0OKI", category: "🥊 Luta" },
    { name: "Medal of Honor Heroes", size: "489.21 MB", link: "https://seulink.net/gxqKW", category: "🔫 Tiro (TPS/FPS)" },
    { name: "Mega Man - Powered Up", size: "265.50 MB", link: "https://seulink.net/S6TPKr1bJX", category: "🎮 Plataforma / Puzzle / Família" },
    { name: "Metal Slug XX", size: "178.91 MB", link: "https://seulink.net/KKq2aTsvX", category: "🔫 Tiro (TPS/FPS)" },
    { name: "Miami Vice - The Game", size: "225.36 MB", link: "https://seulink.net/SAYUuydVap", category: "🔫 Tiro (TPS/FPS)" },
    { name: "Midnight Club - L.A. Remix", size: "434.74 MB", link: "https://seulink.net/9kstT", category: "🏎️ Corrida" },
    { name: "Monster Hunter Freedom", size: "633.61 MB", link: "https://seulink.net/lXnHosGFHg", category: "🧙‍♂️ RPG / Ação" },
    { name: "Monster Jam - Path of Destruction", size: "201.25 MB", link: "https://seulink.net/RziMbKqeE", category: "🏎️ Corrida" },
    { name: "Mortal Kombat - Unchained", size: "335.74 MB", link: "https://4br.me/3FJWEN", category: "🥊 Luta" },
    { name: "MTX Mototrax", size: "346.84 MB", link: "https://seulink.net/Y5M5S", category: "🏎️ Corrida" },
    { name: "MX vs. ATV On the Edge", size: "465.02 MB", link: "https://seulink.net/xKYJZe", category: "🏎️ Corrida" },
    { name: "Naruto - Ultimate Ninja Heroes", size: "209.51 MB", link: "https://seulink.net/E8bO5mVhWv", category: "🥊 Luta" },
    { name: "Naruto Shippuden - Ultimate Ninja Heroes 3", size: "409.01 MB", link: "https://seulink.net/KZ4wLFRhU", category: "🥊 Luta" },
    { name: "NBA Street Showdown", size: "295.58 MB", link: "https://seulink.net/2eHvSWY20", category: "🏆 Esportes" },
    { name: "Need for Speed - Most Wanted 5-1-0", size: "178.95 MB", link: "https://seulink.net/SpjHYs", category: "🏎️ Corrida" },
    { name: "Need for Speed - ProStreet", size: "323.40 MB", link: "https://seulink.net/WpqvxO", category: "🏎️ Corrida" },
    { name: "Need for Speed - Underground Rivals", size: "219.37 MB", link: "https://seulink.net/GlpfgaL", category: "🏎️ Corrida" },
    { name: "Pac-Man World Rally", size: "233.75 MB", link: "https://seulink.net/m6kyb04Qx", category: "🏎️ Corrida" },
    { name: "Patapon", size: "210.34 MB", link: "https://seulink.net/VlRFpdGyVA", category: "🧙‍♂️ RPG / Ação" },
    { name: "Patapon 3", size: "379.81 MB", link: "https://4br.me/rwJUdw8s", category: "🧙‍♂️ RPG / Ação" },
    { name: "Peter Jackson's King Kong - The Official Game of the Movie", size: "392.77 MB", link: "https://seulink.net/b2fCuu", category: "🗡️ Ação / Aventura" },
    { name: "Power Stone Collection", size: "305.25 MB", link: "https://seulink.net/a79R", category: "🥊 Luta" },
    { name: "Prince of Persia - The Forgotten Sands", size: "503.56 MB", link: "https://seulink.net/dMx0W", category: "🗡️ Ação / Aventura" },
    { name: "Shepherd's Crossing", size: "157.89 MB", link: "https://4br.me/xURE", category: "🌾 Simulação / Vida" },
    { name: "SOCOM - U.S. Navy SEALs Fireteam Bravo", size: "380.43 MB", link: "https://4br.me/iSiHx", category: "🔫 Tiro (TPS/FPS)" },
    { name: "Sonic Rivals", size: "121.38 MB", link: "https://4br.me/IXjvrEhJmQ", category: "🎮 Plataforma / Puzzle / Família" },
    { name: "Soulcalibur - Broken Destiny", size: "375.45 MB", link: "https://seulink.net/d7QKBW", category: "🥊 Luta" },
    { name: "Spider-Man - Friend or Foe", size: "503.40 MB", link: "https://seulink.net/odHGZdoT", category: "🗡️ Ação / Aventura" },
    { name: "Spider-Man - Web of Shadows", size: "237.09 MB", link: "https://4br.me/p6hbq", category: "🗡️ Ação / Aventura" },
    { name: "Street Fighter Alpha 3 Max", size: "113.55 MB", link: "https://seulink.net/VeyLqOCz7", category: "🥊 Luta" },
    { name: "Surf's Up", size: "491.24 MB", link: "https://seulink.net/54oY3VN9u", category: "🏎️ Corrida" },
    { name: "The Con", size: "416.36 MB", link: "https://seulink.net/SzXf", category: "🥊 Luta" },
    { name: "Tokobot", size: "193.94 MB", link: "https://4br.me/QQwaG42f4", category: "🎮 Plataforma / Puzzle / Família" },
    { name: "Toy Story 3 - The Video Game", size: "180.69 MB", link: "https://seulink.net/jHZ2cE", category: "🎮 Plataforma / Puzzle / Família" },
    { name: "Twisted Metal - Head-On", size: "317.00 MB", link: "https://seulink.net/SMTWsx4", category: "🏎️ Corrida" },
    { name: "Ultimate Ghosts 'n Goblins", size: "272.11 MB", link: "https://seulink.net/y98wWc", category: "🎮 Plataforma / Puzzle / Família" },
    { name: "Undead Knights", size: "341.72 MB", link: "https://4br.me/nMqcsE", category: "🗡️ Ação / Aventura" },
    { name: "Untold Legends - Brotherhood of the Blade", size: "170.30 MB", link: "https://seulink.net/SqFEZZHa", category: "🧙‍♂️ RPG / Ação" },
    { name: "Untold Legends - The Warrior's Code", size: "643.83 MB", link: "https://seulink.net/AWOnmw", category: "🧙‍♂️ RPG / Ação" },
    { name: "Valhalla Knights", size: "371.85 MB", link: "https://seulink.net/XPGhIan8", category: "🧙‍♂️ RPG / Ação" },
    { name: "Virtua Tennis - World Tour", size: "178.35 MB", link: "https://seulink.net/geABuAiEjZ", category: "🏆 Esportes" },
    { name: "Virtua Tennis 3", size: "357.85 MB", link: "https://seulink.net/lhwT", category: "🏆 Esportes" },
    { name: "WipEout Pulse", size: "199.15 MB", link: "https://seulink.net/OMBa39sqRZ", category: "🏎️ Corrida" },
    { name: "WipEout Pure", size: "153.30 MB", link: "https://seulink.net/LGxsyZKVMi", category: "🏎️ Corrida" },
    { name: "Worms - Open Warfare", size: "199.21 MB", link: "https://seulink.net/OZlPnL8", category: "🎮 Plataforma / Puzzle / Família" },
    { name: "X-Men Origins - Wolverine", size: "439.66 MB", link: "https://seulink.net/Q7FQrWqH3", category: "🗡️ Ação / Aventura" }
];

window.gamesData = gamesData;