const gamesData = [
    { name: "007 From Russia with Love", size: "539.48 MB", link: "https://seulink.net/BZXkMH", category: "🗡️ Ação / Aventura" },
    { name: "101 in 1 Megamix", size: "498.26 MB", link: "https://seulink.net/PLcb0", category: "🎮 Plataforma / Puzzle / Família" },
    { name: "300 - March to Glory", size: "687.78 MB", link: "https://seulink.net/MlYYFJe", category: "🗡️ Ação / Aventura" },
    { name: "Aliens vs. Predator Requiem", size: "279.62 MB", link: "https://seulink.net/T3Gl5v08l", category: "🔫 Tiro (TPS/FPS)" },
    { name: "Ape Escape Academy", size: "158.41 MB", link: "https://seulink.net/jyf6ORhh5", category: "🎮 Plataforma / Puzzle / Família" },
    { name: "Armored Core 3 Portable", size: "299.72 MB", link: "https://seulink.net/HXvamWKXgn", category: "🗡️ Ação / Aventura" },
    { name: "Army of Two - The 40th Day", size: "677.81 MB", link: "https://seulink.net/qn3zDjUJ", category: "🔫 Tiro (TPS/FPS)" },
    { name: "Assassin's Creed Bloodlines", size: "541.94 MB", link: "https://seulink.net/yhSBc47zt", category: "🗡️ Ação / Aventura" },
    { name: "Avatar The Last Airbender", size: "126.70 MB", link: "https://4br.me/E9sms", category: "🗡️ Ação / Aventura" },
    { name: "Battlezone", size: "165.88 MB", link: "https://seulink.net/hdvzq1hi04qzuri", category: "🚗 Combate Veicular" },
    { name: "Ben 10 - Alien Force", size: "761.01 MB", link: "https://seulink.net/4Swh98zAT4", category: "🗡️ Ação / Aventura" },
    { name: "Ben 10 Protector of Earth", size: "593.00 MB", link: "https://seulink.net/v33WNDu", category: "🗡️ Ação / Aventura" },
    { name: "Bomberman", size: "55.83 MB", link: "https://seulink.net/OAEY", category: "🎮 Plataforma / Puzzle / Família" },
    { name: "Burnout Legends", size: "203.82 MB", link: "https://seulink.net/iA0ZvF", category: "🏎️ Corrida" },
    { name: "Cabela's African Safari", size: "432.61 MB", link: "https://seulink.net/3c3FWz", category: "🦌 Simulação de Caça" },
    { name: "Cabela's Legendary Adventures", size: "374.58 MB", link: "https://seulink.net/T4OlYDAKss", category: "🦌 Simulação de Caça" },
    { name: "Cabela's North American Adventures", size: "266.79 MB", link: "https://4br.me/YCE8E5krGR", category: "🦌 Simulação de Caça" },
    { name: "Call of Duty Roads to Victory", size: "478.74 MB", link: "https://seulink.net/YZdJ6pz3", category: "🔫 Tiro (TPS/FPS)" },
    { name: "Chili Con Carnage", size: "595.11 MB", link: "https://4br.me/FoEe5V", category: "🔫 Tiro (TPS/FPS)" },
    { name: "Crash of the Titans", size: "585.42 MB", link: "https://seulink.net/2k07ve", category: "🏃 Plataforma / Aventura" },
    { name: "Dead or Alive - Paradise", size: "568.48 MB", link: "https://seulink.net/ZHFsHfK", category: "🥊 Luta" },
    { name: "Dead to Rights Reckoning", size: "104.21 MB", link: "https://seulink.net/r6pj", category: "🔫 Tiro (TPS/FPS)" },
    { name: "Def Jam Fight for NY The Takeover", size: "389.05 MB", link: "https://seulink.net/YDXkzjxOm", category: "🥊 Luta" },
    { name: "Disney Pixar Toy Story 3", size: "180.69 MB", link: "https://seulink.net/jHZ2cE", category: "🏃 Plataforma / Aventura" },
    { name: "Dragon Ball Z Shin Budokai", size: "208.91 MB", link: "https://4br.me/wMAn33C", category: "🥊 Luta" },
    { name: "Dragoneer's Aria", size: "245.05 MB", link: "https://4br.me/Xe3KByaiT", category: "🧙‍♂️ RPG / Ação" },
    { name: "DreamWorks Shrek the Third", size: "364.54 MB", link: "https://seulink.net/UnTE", category: "🗡️ Ação / Aventura" },
    { name: "Dreamworks Shrek Smash N' Crash", size: "241.12 MB", link: "https://seulink.net/IJe51", category: "🏎️ Corrida" },
    { name: "Dynasty Warriors", size: "115.77 MB", link: "https://seulink.net/4M1D5fRUr", category: "🗡️ Ação / Aventura" },
    { name: "Eragon", size: "162.61 MB", link: "https://seulink.net/qt9mko8", category: "🗡️ Ação / Aventura" },
    { name: "FIFA Street 2", size: "219.07 MB", link: "https://seulink.net/elku", category: "🏆 Esportes" },
    { name: "Fight Night Round 3", size: "522.46 MB", link: "https://4br.me/CeooDWU", category: "🥊 Luta" },
    { name: "FlatOut - Head On", size: "365.48 MB", link: "https://seulink.net/RPvFfwfM", category: "🏎️ Corrida" },
    { name: "Ford Racing Off Road", size: "334.98 MB", link: "https://seulink.net/7apu3c1Gu", category: "🏎️ Corrida" },
    { name: "GUN Showdown", size: "601.54 MB", link: "https://seulink.net/s1Ezi", category: "🔫 Tiro (TPS/FPS)" },
    { name: "Ghost Rider", size: "721.15 MB", link: "https://seulink.net/9ofT4CN", category: "🗡️ Ação / Aventura" },
    { name: "Gladiator Begins", size: "341.59 MB", link: "https://seulink.net/ix851vM1zT", category: "🗡️ Ação / Aventura" },
    { name: "God of War Chains of Olympus", size: "1.03 GB", link: "https://seulink.net/9fK8ParM49", category: "🗡️ Ação / Aventura" },
    { name: "God of War Ghost of Sparta", size: "1018.86 MB", link: "https://seulink.net/jftTXc", category: "🗡️ Ação / Aventura" },
    { name: "Grand Theft Auto Chinatown Wars", size: "493.65 MB", link: "https://seulink.net/STT5PJn", category: "🌍 Mundo Aberto / Sandbox" },
    { name: "Grand Theft Auto Liberty City Stories", size: "316.07 MB", link: "https://seulink.net/6cXbgzBds7", category: "🌍 Mundo Aberto / Sandbox" },
    { name: "Grand Theft Auto Vice City Stories", size: "537.44 MB", link: "https://seulink.net/zPSs9EjZ", category: "🌍 Mundo Aberto / Sandbox" },
    { name: "Hannspree Ten Kate Honda SBK", size: "150.60 MB", link: "https://seulink.net/uBiz5yOHW", category: "🏎️ Corrida" },
    { name: "Harvest Moon Boy & Girl", size: "136.86 MB", link: "https://seulink.net/uUoNJ1teI", category: "🌾 Simulação / Vida" },
    { name: "Harvest Moon Hero of Leaf Valley", size: "137.21 MB", link: "https://seulink.net/h1DMKzv", category: "🌾 Simulação / Vida" },
    { name: "Hot Wheels Ultimate Racing", size: "105.95 MB", link: "https://seulink.net/clOTbT", category: "🏎️ Corrida" },
    { name: "Infected", size: "529.81 MB", link: "https://seulink.net/djKokt7", category: "🔫 Tiro (TPS/FPS)" },
    { name: "Kao Challengers", size: "389.89 MB", link: "https://seulink.net/PYJBsT7", category: "🏃 Plataforma / Aventura" },
    { name: "Kenka Bancho - Badass Rumble", size: "376.69 MB", link: "https://seulink.net/uQ0jBlTWT", category: "🗡️ Ação / Aventura" },
    { name: "Killzone Liberation", size: "477.13 MB", link: "https://seulink.net/CVQf", category: "🔫 Tiro (TPS/FPS)" },
    { name: "LEGO Batman The Video Game", size: "374.81 MB", link: "https://seulink.net/ydS8eLSb", category: "🗡️ Ação / Aventura" },
    { name: "LEGO Indiana Jones", size: "486.31 MB", link: "https://seulink.net/zzn1zTwlXD", category: "🗡️ Ação / Aventura" },
    { name: "MTX Mototrax", size: "346.84 MB", link: "https://seulink.net/Y5M5S", category: "🏎️ Corrida" },
    { name: "MX vs. ATV On the Edge", size: "465.02 MB", link: "https://seulink.net/xKYJZe", category: "🏎️ Corrida" },
    { name: "Marvel Nemesis Rise of the Imperfects", size: "121.66 MB", link: "https://4br.me/s4q0OKI", category: "🥊 Luta" },
    { name: "Medal of Honor Heroes", size: "489.21 MB", link: "https://seulink.net/gxqKW", category: "🔫 Tiro (TPS/FPS)" },
    { name: "Miami Vice The Game", size: "225.36 MB", link: "https://seulink.net/SAYUuydVap", category: "🔫 Tiro (TPS/FPS)" },
    { name: "Midnight Club L.A. Remix", size: "434.74 MB", link: "https://seulink.net/9kstT", category: "🏎️ Corrida" },
    { name: "Monster Hunter Freedom", size: "633.61 MB", link: "https://seulink.net/lXnHosGFHg", category: "🧙‍♂️ RPG / Ação" },
    { name: "Monster Jam Path of Destruction", size: "201.25 MB", link: "https://seulink.net/RziMbKqeE", category: "🚗 Combate Veicular" },
    { name: "Mortal Kombat Unchained", size: "335.74 MB", link: "https://4br.me/3FJWEN", category: "🥊 Luta" },
    { name: "NBA Street Showdown", size: "295.58 MB", link: "https://seulink.net/2eHvSWY20", category: "🏆 Esportes" },
    { name: "Naruto Shippuden Ultimate Ninja Heroes 3", size: "409.01 MB", link: "https://seulink.net/KZ4wLFRhU", category: "🥊 Luta" },
    { name: "Naruto Ultimate Ninja Heroes", size: "209.51 MB", link: "https://seulink.net/E8bO5mVhWv", category: "🥊 Luta" },
    { name: "Need for Speed Most Wanted 5-1-0", size: "178.95 MB", link: "https://seulink.net/SpjHYs", category: "🏎️ Corrida" },
    { name: "Need for Speed ProStreet", size: "323.40 MB", link: "https://seulink.net/WpqvxO", category: "🏎️ Corrida" },
    { name: "Need for Speed Underground Rivals", size: "219.37 MB", link: "https://seulink.net/jvHO0wuE", category: "🏎️ Corrida" },
    { name: "Obscure The Aftermath", size: "811.34 MB", link: "https://seulink.net/LNkIe8lO", category: "👻 Survival Horror" },
    { name: "PES 2010 - Pro Evolution Soccer", size: "864.69 MB", link: "https://seulink.net/5fH6OXD", category: "🏆 Esportes" },
    { name: "Pac-Man World Rally", size: "233.75 MB", link: "https://seulink.net/m6kyb04Qx", category: "🏎️ Corrida" },
    { name: "Patapon 3", size: "379.81 MB", link: "https://4br.me/rwJUdw8s", category: "🎮 Plataforma / Puzzle / Família" },
    { name: "Peter Jackson's King Kong", size: "392.77 MB", link: "https://seulink.net/b2fCuu", category: "🗡️ Ação / Aventura" },
    { name: "Prince of Persia - The Forgotten Sands", size: "503.56 MB", link: "https://seulink.net/dMx0W", category: "🗡️ Ação / Aventura" },
    { name: "Prince of Persia Rival Swords", size: "1010.46 MB", link: "https://seulink.net/x4sUV", category: "🗡️ Ação / Aventura" },
    { name: "Pursuit Force", size: "728.75 MB", link: "https://seulink.net/pQLNR", category: "🏎️ Corrida / Ação" },
    { name: "SOCOM U.S. Navy SEALs Fireteam", size: "380.43 MB", link: "https://4br.me/iSiHx", category: "🔫 Tiro (TPS/FPS)" },
    { name: "Shepherd's Crossing", size: "157.89 MB", link: "https://4br.me/xURE", category: "🌾 Simulação / Vida" },
    { name: "Silent Hill Origins", size: "708.38 MB", link: "https://seulink.net/tdvxnH5A", category: "👻 Survival Horror" },
    { name: "Sonic Rivals", size: "121.22 MB", link: "https://4br.me/IXjvrEhJmQ", category: "🏃 Plataforma / Aventura" },
    { name: "Soulcalibur Broken Destiny", size: "375.45 MB", link: "https://seulink.net/d7QKBW", category: "🥊 Luta" },
    { name: "Spider Man Friend or Foe", size: "503.40 MB", link: "https://seulink.net/odHGZdoT", category: "🗡️ Ação / Aventura" },
    { name: "Spider Man Web of Shadows", size: "237.09 MB", link: "https://4br.me/p6hbq", category: "🗡️ Ação / Aventura" },
    { name: "Street Fighter Alpha 3 Max", size: "113.55 MB", link: "https://seulink.net/VeyLqOCz7", category: "🥊 Luta" },
    { name: "Surf's Up", size: "491.24 MB", link: "https://seulink.net/54oY3VN9u", category: "🏎️ Corrida" },
    { name: "Syphon Filter - Logan's Shadow", size: "1.07 GB", link: "https://seulink.net/JEnd", category: "🔫 Tiro (TPS/FPS)" },
    { name: "Tekken - Dark Resurrection", size: "1.15 GB", link: "https://seulink.net/N7OS6I6TQA", category: "🥊 Luta" },
    { name: "Twisted Metal Head On", size: "317.00 MB", link: "https://seulink.net/SMTWsx4", category: "🚗 Combate Veicular" },
    { name: "Ultimate Ghosts'n Goblins", size: "272.11 MB", link: "https://seulink.net/y98wWc", category: "🏃 Plataforma / Aventura" },
    { name: "Undead Knights", size: "341.72 MB", link: "https://4br.me/nMqcsE", category: "🗡️ Ação / Aventura" },
    { name: "Untold Legends - The Warrior's Code", size: "643.83 MB", link: "https://seulink.net/AWOnmw", category: "🧙‍♂️ RPG / Ação" },
    { name: "Virtua Tennis - World Tour", size: "178.35 MB", link: "https://seulink.net/geABuAiEjZ", category: "🏆 Esportes" },
    { name: "Virtua Tennis 3", size: "357.85 MB", link: "https://seulink.net/lhwT", category: "🏆 Esportes" },
    { name: "WipeOut Pure", size: "153.30 MB", link: "https://seulink.net/LGxsyZKVMi", category: "🏎️ Corrida" },
    { name: "Worms Open Warfare", size: "199.21 MB", link: "https://seulink.net/OZlPnL8", category: "🎮 Plataforma / Puzzle / Família" },
    { name: "X-Men Origins Wolverine", size: "440.58 MB", link: "https://seulink.net/Q7FQrWqH3", category: "🗡️ Ação / Aventura" },
    { name: "Xiaolin Showdown", size: "328.28 MB", link: "https://seulink.net/xeiBYlAR", category: "🥊 Luta" }
];

window.gamesData = gamesData;